### ISSUE TITLE
(1.12) palette has no recipe

### ISSUE THREAD

**Issue by majijn** [ercanserteli/xercamods#11]

**Comment by ercanserteli** [comment]
Does the recipe shown in the mod page not work for you?

**Comment by majijn** [comment]
adding new dyes works, but not crafting the first palette (sorry for taking long to answer i have been ill)

**Comment by ercanserteli** [comment]
I tested this again and it works:
![resim](https://user-images.githubusercontent.com/9050561/95440034-15f83d80-0961-11eb-9f54-6594054f180e.png)

If you mean you can't craft a palette with no colors, yes you can't because that would be the slab's crafting recipe. And there is no reason to craft an empty palette anyways.

I thought of using clay instead of planks but it is too late at this point.

**Comment by majijn** [comment]
no i mean i cant craft palettes, if i cheat one in i can add colours to it, but i cant craft a basic one
