### ISSUE TITLE
Increase rarity of enchantments

### ISSUE THREAD

**Issue by TheDeviantCrafter** [ercanserteli/xercamods#13]
Enchantments like guillotine and uppercut show up far too frequently when enchanting books. In my testing it was about half of all enchantments, which make vanilla enchantments unreasonably hard to obtain.

**Comment by ercanserteli** [comment]
Will check.

**Comment by ercanserteli** [comment]
You are right. There are 47 vanilla vs 14 xercamod enchantments (ratio = 3.3) but when I enchant an inventory full of books I got 27 vanilla vs 19 xercamod enchantments (ratio = 1.4).  It looks like rarity should be at least doubled on average. Which is strange because I copied similar vanilla enchantment's rarities when adding new enchantments. Anyways, will try to fix it.

**Comment by TheDeviantCrafter** [comment]
The enchantments are also fairly niche. The average player won't need very many of them. I think they should be rarer then vanilla enchantments so that randomly enchanting books is likely to give something valuable to everyone.

**Comment by ercanserteli** [comment]
Fixed 153deb670c170ec3c314adffefe00deea6cc41f7

Testing with the new settings, I got 33 vanilla to 9 xercamod enchantments in books.
