### ISSUE TITLE
Problems with Voice of God in loot chest

### ISSUE THREAD

**Issue by pwigary** [ercanserteli/xercamods#38]
Would like to play this with my friends, however we had discovered that the "Voice of God" spawn too frequently in the loot chest around the world, which is fine normally, but we have another mod that have important items in the loot chest for game progressions. (we are using the endremaster mod btw). So, it result in the Voice of God replacing those items. Unfortunately for now we have to removed it for the game progression to happen. I hope you guys could add a config to disable the spawning for that in the loot chest, and also if there's any trades from villagers. We could add a custom recipe for it via craft tweaker later on. Thank you.

pictures for reference:

https://ibb.co/zRFsykm
https://ibb.co/2NQ5jHq
https://ibb.co/FzqyZ5m
https://ibb.co/tqW3h0J

**Comment by koderian** [comment]
Same issue.

**Comment by ercanserteli** [comment]
This issue is now fixed in the latest version 5c3c591f. Apparently it was overriding other mods' loot tables #39 . That should now be fixed, and the item will appear much less often and only in desert temples. 

If you would like to disable it spawning completely, you can find data/xercamusic/loot_modifiers/temple_vog.json inside the jar file, extract it and change the chance value from 0.1 to 0, and create a datapack with that modified file in order to override the one in the mod.
