### ISSUE TITLE
No grass seeds

### ISSUE THREAD

**Issue by cdevine-xom** [ercanserteli/xercamods#7]
Grass doesn't drop the seeds it would otherwise drop in vanilla. Turning off the tea and food modules fixes the issue

**Comment by ercanserteli** [comment]
Hmm, which seeds do you mean? In vanilla, grass only drops wheat seeds and I just tested with tea/food enabled and saw that it still drops those (in addition to xercamod seeds). Does it not drop for you?

**Comment by SirCaptainCaleb** [comment]
(It's me again). I meant wheat seeds, but on this matter, nothing whatsoever drops for me from grass when this option is enabled. However, since it works for you there may be a compatibility issue with another mod. If the problem keeps occurring I'll let you know

**Comment by SirCaptainCaleb** [comment]
Okay, fixed it. Here's the details. I was using the 1.14 version, and noticed in the debug log that some tomato and tea models were missing and giving errors. So I took your most recent 1.15 version, and made it compatible with 1.14. Unfortunately, this was just a waste of time, because the problem was the mod "Mystical World" was messing up the grass drops. The up side to all of this, is that I now have a 1.14 version of your mod with all the 1.15 version's content.

**Comment by ercanserteli** [comment]
Thanks for the update, that's interesting. I'm glad the mystery is solved and you ended up getting some bonus content :) . If you wish to share your new 1.14 version with the world, you can open a pull request to the master branch, but don't feel a need to do it.

**Comment by ercanserteli** [comment]
Thanks for the pull request, I fixed a few things but now it's up on curse forge as well.

**Comment by SirCaptainCaleb** [comment]
Thank you for fixing the bug! I didn't fully test it before pushing.
