### ISSUE TITLE
[Joy of Painting] No Crafting Recipe for the Palette

### ISSUE THREAD

**Issue by Aristeaa** [ercanserteli/xercamods#98]
On **Joy of Painting 1.20.1-1.0.0** and as long as i can remember, the recipe for the Palette hasnt worked. People on my server keep asking what the recipe is. Maybe you could add a recipe for an "Empty Palette"? I hope it would be pretty easy to add :)

And then, maybe later on, you can add the recipe for adding dyes to the palette, since the rotating recipes are a bit harder to add.
(im assuming btw, i dont have much experience with doing recepies for mods.)

Thank you for the amazing mods!

**Comment by ercanserteli** [comment]
![image](https://github.com/ercanserteli/xercamods/assets/9050561/1cec130e-fe7c-4814-aec2-6d79636af12d)
I just tested to be sure and it works normally on 1.20.1-1.0.0. You can use any dye in the recipe. There is no recipe for empty palette because three horizontal planks make a slab. I thought about changing the material but the recipe has been established for some time, so I don't want to confuse the players that have been using it.
